stages:
  - analyze

sonarqube:
  stage: analyze
  image: <container-registry-url>/mycompany/sonar-scanner-msbuild:6.0
  script:
    - dotnet ./sonar/SonarScanner.MSBuild.dll begin /k:"poc-tsql-code-analysis" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN"
    - dotnet build SqlProject/Database1.sqlproj /t:Rebuild /p:Configuration=Release
    - dotnet ./sonar/SonarScanner.MSBuild.dll end /d:sonar.login="$SONAR_TOKEN"
  variables:
    SONAR_HOST_URL: "https://your-sonarqube-server"
    SONAR_TOKEN: "$SONAR_TOKEN"
